services:
  envoy:
    build:
      context: .
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-fault-injection
    platform: linux/amd64
    volumes:
    - ./runtime:/srv/runtime
    ports:
    - 9211:9211

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
    - ${PORT_PROXY:-8080}:80
